retrieve (1)/src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questionaire__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <displayFormat>Option-{000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve (1)/src/objects/Questionaire__c.object
<CustomObject>
    <fields>
        <fullName>Option1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Option1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option1)</relationshipLabel>
        <relationshipName>Questionaires3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option2)</relationshipLabel>
        <relationshipName>Questionaires4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option3</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option3)</relationshipLabel>
        <relationshipName>Questionaires5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option4</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option4)</relationshipLabel>
        <relationshipName>Questionaires6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Solution1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires</relationshipLabel>
        <relationshipName>Questionaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Solution 2)</relationshipLabel>
        <relationshipName>Questionaires1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>ADM 201</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEV 401</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Cloud</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questionaire</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Questionaire Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve (1)/src/classes/Test_Page2Controller.cls
@isTest
public class Test_Page2Controller {
public static TestMethod void test1(){

Questionaire__c q = new Questionaire__c();
  q.question__c ='On Lead Conversion a Lead Object Custom field cannot be mapped to Which Object custom field?';
  q.type__c = 'ADM 201';
  insert q;
  
  Option__c opt = new Option__c();
  opt.option__c = 'Account';
  opt.question__c = q.id;
  insert opt;
  
  Option__c opt1 = new Option__c();
  opt1.option__c = 'Contact';
  opt1.question__c = q.id;
  insert opt1;
  
  Option__c opt2 = new Option__c();
  opt2.option__c = 'Case';
  opt2.question__c = q.id;
  insert opt2;
  
  Option__c opt3 = new Option__c();
  opt3.option__c = 'Opportunity';
  opt3.question__c = q.id;
  insert opt3;
  
  q.option1__c = opt.id;
  q.option2__c = opt1.id;
  q.option3__c = opt2.id;
  q.option4__c = opt3.id;
  q.solution1__c = opt2.id;
  q.solution2__c =opt1.id;
  update q;
  
  page2Controller pc = new page2Controller();
 // pc.testCategory = 'two';
  pc.clicked();
  pc.clicked1();
  pc.clicked2();
  pc.clicked3();
  system.assertEquals(pc.flag,true);
  system.assertEquals(pc.flag1,true);
  system.assertEquals(pc.flag2,true);
  system.assertEquals(pc.flag3,true);
  
  pageReference p = pc.adm();
  system.assertEquals('/apex/playpage?time=null&type=adm',p.getURL());
  pc.adm1();
  pc.admLearn();
  pageReference p1 = pc.dev();
  system.assertEquals('/apex/playpage?time=null&type=dev',p1.getURL());
  pc.dev1();
  pc.devLearn();
  pageReference p2 = pc.sales();
  system.assertEquals('/apex/playpage?time=null&type=sales',p2.getURL());
  pc.sales1();
  pc.salesLearn();
  pageReference p3 = pc.service();
  system.assertEquals('/apex/playpage?time=null&type=service',p3.getURL());
  pc.service1();
  pc.serviceLearn();
  
 }
 
 }