retrieve (1)/src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questionaire__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <displayFormat>Option-{000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve (1)/src/objects/Questionaire__c.object
<CustomObject>
    <fields>
        <fullName>Option1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Option1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option1)</relationshipLabel>
        <relationshipName>Questionaires3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option2)</relationshipLabel>
        <relationshipName>Questionaires4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option3</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option3)</relationshipLabel>
        <relationshipName>Questionaires5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option4</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option4)</relationshipLabel>
        <relationshipName>Questionaires6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Solution1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires</relationshipLabel>
        <relationshipName>Questionaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Solution 2)</relationshipLabel>
        <relationshipName>Questionaires1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>ADM 201</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEV 401</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Cloud</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questionaire</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Questionaire Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve (1)/src/classes/Test_PlayController1.cls
@isTest(seeAllData=true)
public class Test_PlayController1 {
public static String wrong;

      
public static TestMethod void test1(){
     Map<String,ID> profiles = new Map<String,ID>();
     List<Profile> ps = [select id, name from Profile where name = 
         'Standard User' or name = 'System Administrator'];

      for(Profile p : ps){
         profiles.put(p.name, p.id);
      }
      User standard = new User(alias = 'standt', 
      email='standarduser@testorg.com', 
      emailencodingkey='UTF-8', 
      lastname='Testing', languagelocalekey='en_US', 
      localesidkey='en_US', Points_Gained__c = 20,
      profileid = profiles.get('System Administrator'), 
      timezonesidkey='America/Los_Angeles', 
      username='funlearnuser@testorg.com');

      insert standard;

  Questionaire__c q = new Questionaire__c();
  q.question__c ='On Lead Conversion a Lead Object Custom field cannot be mapped to Which Object custom field?';
  q.type__c = 'ADM 201';
  insert q;
  
  Questionaire__c q1 = new Questionaire__c();
  q1.question__c ='On Lead Conversion a Lead Object Custom field cannot be mapped to Which Object custom field?';
  q1.type__c = 'ADM 201';
  insert q1;
  
  Questionaire__c q2 = new Questionaire__c();
  q2.question__c ='On Lead Conversion a Lead Object Custom field cannot be mapped to Which Object custom field?';
  q2.type__c = 'ADM 201';
  insert q2;
  
   Option__c opt = new Option__c();
  opt.option__c = 'Account';
  opt.question__c = q.id;
  insert opt;
  
  Option__c opt1 = new Option__c();
  opt1.option__c = 'Contact';
  opt1.question__c = q.id;
  insert opt1;
  
  Option__c opt2 = new Option__c();
  opt2.option__c = 'Case';
  opt2.question__c = q.id;
  insert opt2;
  
  Option__c opt3 = new Option__c();
  opt3.option__c = 'Opportunity';
  opt3.question__c = q.id;
  insert opt3;
  
  q.option1__c = opt.id;
  q.option2__c = opt1.id;
  q.option3__c = opt2.id;
  q.option4__c = opt3.id;
  q.solution1__c = opt2.id;
  q.solution2__c =opt1.id;
  update q;
  
  q1.option1__c = opt.id;
  q1.option2__c = opt1.id;
  q1.option3__c = opt2.id;
  q1.option4__c = opt3.id;
  q1.solution1__c = opt2.id;
  q1.solution2__c =opt1.id;
  update q1;
  
  q2.option1__c = opt.id;
  q2.option2__c = opt1.id;
  q2.option3__c = opt2.id;
  q2.option4__c = opt3.id;
  q2.solution1__c = opt2.id;
  q2.solution2__c =opt1.id;
  update q2;
  Set<String> wrongs = new Set<String>();
  wrongs.add(q.id);
  wrongs.add(q1.id);
  wrongs.add(q2.id);
  system.runas(standard){
  ApexPages.currentPage().getParameters().put('time', 'two');
  ApexPages.currentPage().getParameters().put('type', 'adm');
  playController1 p1 = new playController1();
  p1.check1=true;
  p1.check2=true;
  p1.check3=true;
  p1.check4=true;
 // p1.wrongQues=wrongs;
 // p1.lifelinesUsed = 0;
 
  list<SelectOption> myopt = p1.getOptions();
  System.assertEquals(myopt.size(),4);
  p1.submitAns();
  p1.showWrongs();
  p1.done();
  p1.returnResult();
  
  p1.redeemPoints();
  p1.quit();
  }
  }
  
  }