retrieve (1)/src/objects/Option__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Questionaire__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option</label>
    <nameField>
        <displayFormat>Option-{000}</displayFormat>
        <label>Option Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieve (1)/src/objects/Questionaire__c.object
<CustomObject>
    <fields>
        <fullName>Multi_Select__c</fullName>
        <formula>IF((Solution1__c !=null &amp;&amp; Solution2__c == null &amp;&amp; Solution3__c == null),FALSE,TRUE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Multi-Select</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Multiselect__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Multiselect?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Option1__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Option1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option1)</relationshipLabel>
        <relationshipName>Questionaires3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option2)</relationshipLabel>
        <relationshipName>Questionaires4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option3</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option3)</relationshipLabel>
        <relationshipName>Questionaires5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Option4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Option4</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Option4)</relationshipLabel>
        <relationshipName>Questionaires6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Solution1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 1</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires</relationshipLabel>
        <relationshipName>Questionaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 2</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Solution 2)</relationshipLabel>
        <relationshipName>Questionaires1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution 3</label>
        <referenceTo>Option__c</referenceTo>
        <relationshipLabel>Questionaires (Solution 3)</relationshipLabel>
        <relationshipName>Questionaires2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionaire</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Questionaire Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieve (1)/src/classes/playController2.cls
public with sharing class playController2 {
public List<Questionaire__c> questions {get;set;}
public Questionaire__c currQuestion1 {get;set;}
public integer counter1 {get;set;}
public boolean completed1 {get;set;}
public boolean check5 {get;set;}
public String wrongIds {get;set;}
public List<String> wrong {get;set;}
public String answer1 {get;set;}
public List<SelectOption> options;
public String total {get;set;}
public String correct {get;set;}
public boolean myflag {get;set;}

public playController2(){
myflag=false;
wrongIds = apexpages.currentpage().getparameters().get('wrong');
if(apexpages.currentpage().getparameters().get('total')!=null || apexpages.currentpage().getparameters().get('total')!='')
      total = apexpages.currentpage().getparameters().get('total');
   if(apexpages.currentpage().getparameters().get('correct')!=null || apexpages.currentpage().getparameters().get('correct')!='')
      correct = apexpages.currentpage().getparameters().get('correct');
system.debug('========param-------'+wrongIds);
wrong = new list<String>();
counter1 = 0;
String[] strArr =WrongIds.split('ATR');
system.debug('===strArr=='+strArr);
for(String s : strArr){
  wrong.add(s);
}
 system.debug('============wrong========'+wrong);
 questions = [SELECT Option1__c,Option1__r.Option__c,Option2__c,Option2__r.Option__c,Option3__r.Option__c,Option3__c,Option4__c,Option4__r.option__c,OwnerId,Question__c,Solution1__c,Solution1__r.option__c,Solution2__c,Solution2__r.option__c,Solution3__c,Solution3__r.option__c,multiselect__c,Multi_Select__c FROM Questionaire__c where id IN:strArr];
counter1 = 0;
currQuestion1 =  questions[0];
completed1 = false;
//questions = new List<Questionaire__c>();
}

public void showWrongQuestions(){
    system.debug('----------in here----------');
     counter1 = 0;
     questions = [SELECT Option1__c,Option1__r.Option__c,Option2__c,Option2__r.Option__c,Option3__r.Option__c,Option3__c,Option4__c,Option4__r.option__c,OwnerId,Question__c,Solution1__c,Solution1__r.option__c,Solution2__c,Solution2__r.option__c,Solution3__c,Solution3__r.option__c,multiselect__c,Multi_Select__c FROM Questionaire__c where id IN:wrong];
     currQuestion1 =  questions[0];
     system.debug('----------in here----------'+currQuestion1);

  }
  
  public void nextQues(){
  if(counter1<questions.size() && questions.size()!=1 ){
    counter1=counter1+1;
    currQuestion1 =  questions[counter1];
    if(currQuestion1.Multi_Select__c == true)
      myflag=true;
    else 
       myflag=false;  
    }
    if(counter1 >= (questions.size()-1)){
      completed1 = true;
      
    }
    }
      
  public list<SelectOption> getOptions()
  {
    list<SelectOption> options = new list<SelectOption>();
    
    options.add(new SelectOption(currquestion1.Option1__c, currquestion1.Option1__r.Option__c));
    options.add(new SelectOption(currquestion1.Option2__c, currquestion1.Option2__r.Option__c));
    if(currquestion1.Option3__c!=null)
    options.add(new SelectOption(currquestion1.Option3__c, currquestion1.Option3__r.Option__c));
    if(currquestion1.Option4__c!=null)
    options.add(new SelectOption(currquestion1.Option4__c, currquestion1.Option4__r.Option__c));

    return options;
  } 
  
   public pagereference done(){
    return new pageReference('/apex/Congratulationspage?wrong='+WrongIds+'&total='+total+'&correct='+correct); 
  
  }
  }